/// Sample video URLs (YouTube or direct MP4) for curated places.
const _videoCoxs = 'https://www.youtube.com/watch?v=JxwKXiJZ8kY';
const _videoSylhet = 'https://www.youtube.com/watch?v=0-m5SgUq5-4';
const _videoDhaka = 'https://www.youtube.com/watch?v=0-bzALk4puk';
const _videoSundarbans = 'https://www.youtube.com/watch?v=6BCSVkPhx0I';
const _videoMp4 =
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4';

/// Hand-picked places for districts with known tourist spots.
/// Each district should have up to 4 entries; missing slots are filled by templates.
final Map<String, List<Map<String, dynamic>>> curatedPlacesByDistrict = {
  'dhaka': [
    _p(
      name: 'Ahsan Manzil',
      nameBn: 'আহসান মঞ্জিল',
      description:
          'The Pink Palace — former residence of the Nawabs of Dhaka, now a museum.',
      lat: 23.7095,
      lng: 90.3972,
      entryFee: 100,
      isFree: false,
      rating: 4.4,
      reviews: 2200,
      tags: ['museum', 'heritage', 'history'],
      videos: [_videoDhaka, _videoMp4],
    ),
    _p(
      name: 'Lalbagh Fort',
      nameBn: 'লালবাগ কেল্লা',
      description:
          '17th-century Mughal fort complex with a tomb, mosque and museum.',
      lat: 23.7197,
      lng: 90.3888,
      entryFee: 200,
      isFree: false,
      rating: 4.3,
      reviews: 1800,
      tags: ['fort', 'mughal', 'heritage'],
    ),
    _p(
      name: 'National Botanical Garden',
      nameBn: 'জাতীয় উদ্ভিদ উদ্যান',
      description:
          '208-acre garden with thousands of plant species, lakes and walking trails.',
      lat: 23.7761,
      lng: 90.3526,
      entryFee: 30,
      isFree: false,
      rating: 4.2,
      reviews: 950,
      tags: ['garden', 'nature', 'family'],
    ),
    _p(
      name: 'Liberation War Museum',
      nameBn: 'মুক্তিযুদ্ধ জাদুঘর',
      description:
          'Museum documenting the 1971 Bangladesh Liberation War.',
      lat: 23.7545,
      lng: 90.3862,
      entryFee: 20,
      isFree: false,
      rating: 4.6,
      reviews: 1400,
      tags: ['museum', 'history', 'heritage'],
    ),
  ],
  'coxs-bazar': [
    _p(
      name: 'Laboni Beach',
      nameBn: 'লাবণী বিচ',
      description:
          "The most accessible and popular beach in Cox's Bazar.",
      lat: 21.4272,
      lng: 92.0058,
      isFree: true,
      rating: 4.5,
      reviews: 1200,
      tags: ['beach', 'sunset', 'popular'],
      videos: [_videoCoxs],
    ),
    _p(
      name: 'Himchari',
      nameBn: 'হিমছড়ি',
      description: 'Scenic hilltop viewpoint with a waterfall and sea views.',
      lat: 21.35,
      lng: 91.9833,
      entryFee: 50,
      isFree: false,
      rating: 4.3,
      reviews: 850,
      tags: ['waterfall', 'nature'],
    ),
    _p(
      name: 'Inani Beach',
      nameBn: 'ইনানী বিচ',
      description: 'Pristine beach with coral rocks and clear water.',
      lat: 21.3,
      lng: 91.9667,
      isFree: true,
      rating: 4.7,
      reviews: 980,
      tags: ['beach', 'coral', 'scenic'],
    ),
    _p(
      name: "Saint Martin Island",
      nameBn: 'সেন্ট মার্টিন দ্বীপ',
      description: "Bangladesh's only coral island with reefs and blue water.",
      lat: 20.6271,
      lng: 92.3209,
      isFree: true,
      visitDuration: 'Full day',
      rating: 4.9,
      reviews: 2100,
      tags: ['island', 'coral', 'diving'],
      videos: [_videoCoxs],
    ),
  ],
  'sylhet': [
    _p(
      name: 'Ratargul Swamp Forest',
      nameBn: 'রাতারগুল সোয়াম্প ফরেস্ট',
      description: "Bangladesh's only freshwater swamp forest, accessible by boat.",
      lat: 25.0,
      lng: 91.9167,
      entryFee: 100,
      isFree: false,
      rating: 4.8,
      reviews: 1500,
      tags: ['forest', 'boat', 'nature'],
      videos: [_videoSylhet],
    ),
    _p(
      name: 'Jaflong',
      nameBn: 'জাফলং',
      description: 'Stone collection point at the Piyain River with border views.',
      lat: 25.15,
      lng: 91.8833,
      entryFee: 20,
      isFree: false,
      rating: 4.4,
      reviews: 1100,
      tags: ['river', 'scenic'],
    ),
    _p(
      name: 'Sreemangal Tea Gardens',
      nameBn: 'শ্রীমঙ্গল চা বাগান',
      description: 'Rolling tea plantations with a misty atmosphere.',
      lat: 24.3061,
      lng: 91.7316,
      isFree: true,
      rating: 4.6,
      reviews: 1300,
      tags: ['tea', 'nature', 'photography'],
    ),
    _p(
      name: 'Shah Jalal Mazar',
      nameBn: 'শাহ জালাল (র.) মাজার',
      description: 'Historic Sufi shrine and spiritual center of Sylhet.',
      lat: 24.8997,
      lng: 91.8707,
      isFree: true,
      rating: 4.5,
      reviews: 890,
      tags: ['shrine', 'heritage', 'spiritual'],
    ),
  ],
  'bandarban': [
    _p(
      name: 'Nilgiri',
      nameBn: 'নীলগিরি',
      description: 'Highest accessible peak with breathtaking cloud views.',
      lat: 21.9,
      lng: 92.2333,
      entryFee: 50,
      isFree: false,
      rating: 4.9,
      reviews: 1800,
      tags: ['hill', 'clouds', 'sunrise'],
    ),
    _p(
      name: 'Boga Lake',
      nameBn: 'বগা লেক',
      description: 'Crater lake nestled deep in the Bandarban hills.',
      lat: 22.0,
      lng: 92.3,
      isFree: true,
      visitDuration: 'Full day (trek)',
      rating: 4.7,
      reviews: 900,
      tags: ['lake', 'trekking', 'adventure'],
    ),
    _p(
      name: 'Chimbuk Hill',
      nameBn: 'চিম্বুক পাহাড়',
      description: 'Third highest peak in Bangladesh, the Queen of Hills.',
      lat: 21.95,
      lng: 92.25,
      isFree: true,
      rating: 4.5,
      reviews: 760,
      tags: ['hill', 'nature', 'photography'],
    ),
    _p(
      name: 'Golden Temple',
      nameBn: 'স্বর্ণ মন্দির',
      description: 'Buddhist temple with golden architecture in Bandarban town.',
      lat: 22.1953,
      lng: 92.2184,
      isFree: true,
      rating: 4.4,
      reviews: 640,
      tags: ['temple', 'heritage', 'culture'],
    ),
  ],
  'chittagong': [
    _p(
      name: 'Patenga Beach',
      nameBn: 'পতেঙ্গা সমুদ্র সৈকত',
      description: 'Popular sea beach near the port with sunsets.',
      lat: 22.2456,
      lng: 91.7861,
      isFree: true,
      rating: 4.2,
      reviews: 1100,
      tags: ['beach', 'sunset'],
    ),
    _p(
      name: "Foy's Lake",
      nameBn: "ফয়'স লেক",
      description: 'Artificial lake with hills and an amusement park.',
      lat: 22.3494,
      lng: 91.8053,
      entryFee: 150,
      isFree: false,
      rating: 4.0,
      reviews: 870,
      tags: ['lake', 'amusement', 'family'],
    ),
    _p(
      name: 'Ethnological Museum',
      nameBn: 'জাতিতাত্ত্বিক জাদুঘর',
      description: 'Museum showcasing the cultures of Bangladesh ethnic groups.',
      lat: 22.3569,
      lng: 91.7832,
      entryFee: 20,
      isFree: false,
      rating: 4.3,
      reviews: 520,
      tags: ['museum', 'culture', 'heritage'],
    ),
    _p(
      name: 'Batali Hill',
      nameBn: 'বাতালি পাহাড়',
      description: 'Scenic viewpoint overlooking Chittagong city and bay.',
      lat: 22.38,
      lng: 91.82,
      isFree: true,
      rating: 4.1,
      reviews: 410,
      tags: ['hill', 'viewpoint', 'scenic'],
    ),
  ],
  'rangamati': [
    _p(
      name: 'Kaptai Lake',
      nameBn: 'কাপ্তাই লেক',
      description:
          'The largest man-made lake in Bangladesh, ringed by hills.',
      lat: 22.5,
      lng: 92.2167,
      isFree: true,
      rating: 4.7,
      reviews: 1200,
      tags: ['lake', 'boat', 'scenic'],
    ),
    _p(
      name: 'Shuvolong Waterfall',
      nameBn: 'শুভলং ঝর্ণা',
      description: 'Waterfall accessible by boat on Kaptai Lake.',
      lat: 22.6,
      lng: 92.15,
      entryFee: 50,
      isFree: false,
      rating: 4.5,
      reviews: 680,
      tags: ['waterfall', 'boat', 'nature'],
    ),
    _p(
      name: 'Hanging Bridge',
      nameBn: 'ঝুলন্ত সেতু',
      description: 'Iconic suspension bridge over Kaptai Lake.',
      lat: 22.64,
      lng: 92.19,
      isFree: true,
      rating: 4.4,
      reviews: 550,
      tags: ['bridge', 'scenic', 'photography'],
    ),
    _p(
      name: 'Rajban Bihar',
      nameBn: 'রাজবন বিহার',
      description: 'Peaceful Buddhist monastery and meditation center.',
      lat: 22.66,
      lng: 92.18,
      isFree: true,
      rating: 4.3,
      reviews: 380,
      tags: ['monastery', 'spiritual', 'heritage'],
    ),
  ],
  'rajshahi': [
    _p(
      name: 'Varendra Research Museum',
      nameBn: 'বরেন্দ্র গবেষণা জাদুঘর',
      description: 'Oldest museum in Bangladesh with archaeological artifacts.',
      lat: 24.3745,
      lng: 88.6042,
      entryFee: 50,
      isFree: false,
      rating: 4.3,
      reviews: 540,
      tags: ['museum', 'archaeology', 'heritage'],
    ),
    _p(
      name: 'Puthia Temple Complex',
      nameBn: 'পুঠিয়া মন্দির',
      description: 'Cluster of 19th-century Hindu temples.',
      lat: 24.35,
      lng: 88.8333,
      entryFee: 30,
      isFree: false,
      rating: 4.5,
      reviews: 720,
      tags: ['temple', 'heritage', 'architecture'],
    ),
    _p(
      name: 'Padma River Ghat',
      nameBn: 'পদ্মা নদী ঘাট',
      description: 'Scenic riverfront along the Padma at Rajshahi.',
      lat: 24.37,
      lng: 88.59,
      isFree: true,
      rating: 4.2,
      reviews: 430,
      tags: ['river', 'sunset', 'scenic'],
    ),
    _p(
      name: 'Bagha Mosque',
      nameBn: 'বাঘা মসজিদ',
      description: 'Historic mosque famous for terracotta ornamentation.',
      lat: 24.2,
      lng: 88.83,
      isFree: true,
      rating: 4.4,
      reviews: 310,
      tags: ['mosque', 'heritage', 'architecture'],
    ),
  ],
  'bagerhat': [
    _p(
      name: 'Sixty Dome Mosque',
      nameBn: 'ষাট গম্বুজ মসজিদ',
      description: 'UNESCO World Heritage Site built in the 15th century.',
      lat: 22.6732,
      lng: 89.7467,
      entryFee: 50,
      isFree: false,
      rating: 4.7,
      reviews: 1100,
      tags: ['mosque', 'unesco', 'heritage'],
    ),
    _p(
      name: 'Karamjal',
      nameBn: 'করমজল',
      description: 'Sundarbans eco-tourism center with crocodile nursery.',
      lat: 22.3,
      lng: 89.8,
      entryFee: 200,
      isFree: false,
      rating: 4.5,
      reviews: 620,
      tags: ['mangrove', 'wildlife', 'boat'],
      videos: [_videoSundarbans],
    ),
    _p(
      name: 'Kotka Beach',
      nameBn: 'কটকা বিচ',
      description: 'Remote Sundarbans beach where deer roam freely.',
      lat: 21.8833,
      lng: 89.65,
      entryFee: 300,
      isFree: false,
      visitDuration: 'Full day',
      openingHours: 'Guided tours only',
      rating: 4.8,
      reviews: 430,
      tags: ['beach', 'wildlife', 'sundarbans'],
    ),
    _p(
      name: 'Mongla Port View',
      nameBn: 'মংলা বন্দর',
      description: 'Gateway to the Sundarbans with river and port scenery.',
      lat: 22.495,
      lng: 89.6,
      isFree: true,
      rating: 4.0,
      reviews: 280,
      tags: ['river', 'port', 'scenic'],
    ),
  ],
  'khulna': [
    _p(
      name: 'Sundarbans Gateway',
      nameBn: 'সুন্দরবন প্রবেশদ্বার',
      description: 'Starting point for Sundarbans boat tours from Khulna.',
      lat: 22.8456,
      lng: 89.5403,
      entryFee: 150,
      isFree: false,
      rating: 4.6,
      reviews: 540,
      tags: ['mangrove', 'boat', 'wildlife'],
    ),
    _p(
      name: 'Rupsha Bridge View',
      nameBn: 'রূপসা সেতু',
      description: 'Iconic bridge over the Rupsha River.',
      lat: 22.82,
      lng: 89.56,
      isFree: true,
      rating: 4.2,
      reviews: 380,
      tags: ['bridge', 'river', 'scenic'],
    ),
    _p(
      name: 'Khulna Shipyard Area',
      nameBn: 'খুলনা শিপইয়ার্ড',
      description: 'Historic shipbuilding area along the riverfront.',
      lat: 22.86,
      lng: 89.52,
      isFree: true,
      rating: 3.9,
      reviews: 210,
      tags: ['river', 'industrial', 'heritage'],
    ),
    _p(
      name: 'Bibir Hat Forest Park',
      nameBn: 'বিবির হাট পার্ক',
      description: 'Local park and green space for families.',
      lat: 22.88,
      lng: 89.55,
      isFree: true,
      rating: 4.0,
      reviews: 190,
      tags: ['park', 'family', 'nature'],
    ),
  ],
  'satkhira': [
    _p(
      name: 'Sundarbans West Entry',
      nameBn: 'সুন্দরবন পশ্চিম প্রবেশ',
      description: 'Western access point to the Sundarbans mangrove forest.',
      lat: 22.7185,
      lng: 89.0705,
      entryFee: 200,
      isFree: false,
      rating: 4.5,
      reviews: 340,
      tags: ['mangrove', 'wildlife', 'boat'],
    ),
    _p(
      name: 'Debhata River View',
      nameBn: 'দেবহাটা নদী',
      description: 'Scenic river and rural landscape in Satkhira.',
      lat: 22.75,
      lng: 89.1,
      isFree: true,
      rating: 4.1,
      reviews: 180,
      tags: ['river', 'nature', 'scenic'],
    ),
    _p(
      name: 'Satkhira Central Park',
      nameBn: 'সাতক্ষীরা সেন্ট্রাল পার্ক',
      description: 'Town park popular with local families.',
      lat: 22.72,
      lng: 89.08,
      isFree: true,
      rating: 3.8,
      reviews: 120,
      tags: ['park', 'family'],
    ),
    _p(
      name: 'Shrimp Farm Trail',
      nameBn: 'চিংড়ি খামার এলাকা',
      description: 'Coastal area known for shrimp cultivation and wetlands.',
      lat: 22.68,
      lng: 89.05,
      isFree: true,
      rating: 4.0,
      reviews: 95,
      tags: ['coastal', 'local', 'nature'],
    ),
  ],
  'patuakhali': [
    _p(
      name: 'Kuakata Beach',
      nameBn: 'কুয়াকাটা সমুদ্র সৈকত',
      description: 'Rare beach where both sunrise and sunset are visible over the sea.',
      lat: 21.8233,
      lng: 90.1192,
      isFree: true,
      rating: 4.8,
      reviews: 1600,
      tags: ['beach', 'sunrise', 'sunset'],
    ),
    _p(
      name: 'Gangamati Reserved Forest',
      nameBn: 'গঙ্গামতি রিজার্ভ ফরেস্ট',
      description: 'Coastal forest near Kuakata with red crab habitat.',
      lat: 21.81,
      lng: 90.1,
      entryFee: 30,
      isFree: false,
      rating: 4.4,
      reviews: 420,
      tags: ['forest', 'nature', 'coastal'],
    ),
    _p(
      name: 'Fatrar Char',
      nameBn: 'ফাতারার চর',
      description: 'Island char with mangroves accessible by boat.',
      lat: 21.85,
      lng: 90.15,
      isFree: true,
      rating: 4.2,
      reviews: 280,
      tags: ['island', 'boat', 'nature'],
    ),
    _p(
      name: 'Patuakhali River Ghat',
      nameBn: 'পটুয়াখালী ঘাট',
      description: 'Busy river port and local market area.',
      lat: 22.3596,
      lng: 90.3297,
      isFree: true,
      rating: 3.9,
      reviews: 150,
      tags: ['river', 'local', 'market'],
    ),
  ],
  'cumilla': [
    _p(
      name: 'Shalban Vihara',
      nameBn: 'শালবন বিহার',
      description: 'Ancient Buddhist archaeological site at Mainamati.',
      lat: 23.45,
      lng: 91.2,
      entryFee: 20,
      isFree: false,
      rating: 4.5,
      reviews: 780,
      tags: ['archaeology', 'heritage', 'buddhist'],
    ),
    _p(
      name: 'Mainamati War Cemetery',
      nameBn: 'মাইনামতি যুদ্ধ কবরস্থান',
      description: 'Commonwealth war cemetery from World War II.',
      lat: 23.44,
      lng: 91.19,
      isFree: true,
      rating: 4.3,
      reviews: 340,
      tags: ['heritage', 'history', 'memorial'],
    ),
    _p(
      name: 'Dharmasagar Lake',
      nameBn: 'ধর্মসাগর',
      description: 'Historic lake in Comilla town.',
      lat: 23.4607,
      lng: 91.1809,
      isFree: true,
      rating: 4.0,
      reviews: 290,
      tags: ['lake', 'heritage', 'scenic'],
    ),
    _p(
      name: 'Lalmai Hills',
      nameBn: 'লালমাই পাহাড়',
      description: 'Low hills with archaeological mounds and trails.',
      lat: 23.42,
      lng: 91.17,
      isFree: true,
      rating: 4.2,
      reviews: 410,
      tags: ['hill', 'archaeology', 'nature'],
    ),
  ],
  'bogra': [
    _p(
      name: 'Mahasthangarh',
      nameBn: 'মহাস্থানগড়',
      description: 'Ancient archaeological site, capital of Pundravardhana.',
      lat: 24.95,
      lng: 89.35,
      entryFee: 20,
      isFree: false,
      rating: 4.6,
      reviews: 920,
      tags: ['archaeology', 'heritage', 'history'],
    ),
    _p(
      name: 'Gokul Medh',
      nameBn: 'গোকুল মেধ',
      description: 'Buddhist stupa mound near Mahasthangarh.',
      lat: 24.94,
      lng: 89.34,
      isFree: true,
      rating: 4.3,
      reviews: 380,
      tags: ['heritage', 'buddhist', 'archaeology'],
    ),
    _p(
      name: 'Vasu Bihar',
      nameBn: 'বাসু বিহার',
      description: 'Excavated Buddhist monastery ruins.',
      lat: 24.93,
      lng: 89.36,
      isFree: true,
      rating: 4.2,
      reviews: 260,
      tags: ['heritage', 'buddhist'],
    ),
    _p(
      name: 'Bogra Town Park',
      nameBn: 'বগুড়া টাউন পার্ক',
      description: 'Central park and green space in Bogra.',
      lat: 24.8481,
      lng: 89.373,
      isFree: true,
      rating: 3.9,
      reviews: 180,
      tags: ['park', 'family'],
    ),
  ],
  'naogaon': [
    _p(
      name: 'Paharpur Buddhist Vihara',
      nameBn: 'পাহাড়পুর বৌদ্ধ বিহার',
      description: 'UNESCO World Heritage Site, largest Buddhist monastery south of Himalayas.',
      lat: 25.0264,
      lng: 88.9769,
      entryFee: 50,
      isFree: false,
      rating: 4.8,
      reviews: 1100,
      tags: ['unesco', 'heritage', 'buddhist'],
    ),
    _p(
      name: 'Kusumba Mosque',
      nameBn: 'কুসুম্বা মসজিদ',
      description: 'Black stone mosque from the Sultanate period.',
      lat: 24.68,
      lng: 88.78,
      isFree: true,
      rating: 4.4,
      reviews: 420,
      tags: ['mosque', 'heritage', 'architecture'],
    ),
    _p(
      name: 'Dibar Dighi',
      nameBn: 'দিবর দীঘি',
      description: 'Ancient man-made pond with local legends.',
      lat: 24.79,
      lng: 88.93,
      isFree: true,
      rating: 4.0,
      reviews: 210,
      tags: ['heritage', 'lake', 'history'],
    ),
    _p(
      name: 'Naogaon Mango Orchards',
      nameBn: 'নওগাঁ আম বাগান',
      description: 'Famous mango-growing region, best visited in summer.',
      lat: 24.7936,
      lng: 88.9318,
      isFree: true,
      bestTime: 'May - July',
      rating: 4.3,
      reviews: 350,
      tags: ['orchard', 'food', 'seasonal'],
    ),
  ],
  'dinajpur': [
    _p(
      name: 'Kantajew Temple',
      nameBn: 'কান্তজীর মন্দির',
      description: 'Magnificent terracotta Hindu temple, a national heritage site.',
      lat: 25.8056,
      lng: 88.65,
      entryFee: 30,
      isFree: false,
      rating: 4.7,
      reviews: 980,
      tags: ['temple', 'heritage', 'architecture'],
    ),
    _p(
      name: 'Ramsagar Lake',
      nameBn: 'রামসাগর',
      description: 'Historic man-made lake built in the 18th century.',
      lat: 25.62,
      lng: 88.64,
      isFree: true,
      rating: 4.3,
      reviews: 520,
      tags: ['lake', 'heritage', 'scenic'],
    ),
    _p(
      name: 'Dinajpur Rajbari',
      nameBn: 'দিনাজপুর রাজবাড়ি',
      description: 'Ruins of the historic palace of Dinajpur kings.',
      lat: 25.6217,
      lng: 88.6354,
      isFree: true,
      rating: 4.1,
      reviews: 340,
      tags: ['palace', 'heritage', 'history'],
    ),
    _p(
      name: 'Shopnopuri Amusement Park',
      nameBn: 'স্বপ্নপুরী',
      description: 'Popular theme park and picnic spot near Dinajpur.',
      lat: 25.58,
      lng: 88.7,
      entryFee: 100,
      isFree: false,
      rating: 4.0,
      reviews: 610,
      tags: ['amusement', 'family', 'park'],
    ),
  ],
  'moulvibazar': [
    _p(
      name: 'Lawachara National Park',
      nameBn: 'লাউয়াছড়া জাতীয় উদ্যান',
      description: 'Tropical rainforest home to the endangered hoolock gibbon.',
      lat: 24.32,
      lng: 91.79,
      entryFee: 100,
      isFree: false,
      rating: 4.7,
      reviews: 890,
      tags: ['forest', 'wildlife', 'nature'],
    ),
    _p(
      name: 'Madhabkunda Waterfall',
      nameBn: 'মাধবকুণ্ড ঝর্ণা',
      description: 'Largest waterfall in Bangladesh.',
      lat: 24.58,
      lng: 91.72,
      entryFee: 50,
      isFree: false,
      rating: 4.5,
      reviews: 720,
      tags: ['waterfall', 'nature', 'scenic'],
    ),
    _p(
      name: 'Tea Garden Trail',
      nameBn: 'চা বাগান',
      description: 'Rolling tea estates characteristic of Moulvibazar.',
      lat: 24.4829,
      lng: 91.7705,
      isFree: true,
      rating: 4.4,
      reviews: 540,
      tags: ['tea', 'nature', 'photography'],
    ),
    _p(
      name: 'Hakaluki Haor',
      nameBn: 'হাকালুকি হাওর',
      description: 'One of the largest wetlands in Asia, rich in birdlife.',
      lat: 24.5,
      lng: 92.0,
      isFree: true,
      bestTime: 'November - March',
      rating: 4.6,
      reviews: 480,
      tags: ['wetland', 'birds', 'nature'],
    ),
  ],
};

Map<String, dynamic> _p({
  required String name,
  required String nameBn,
  required String description,
  required double lat,
  required double lng,
  double entryFee = 0,
  bool isFree = false,
  String visitDuration = '2-3 hours',
  String bestTime = 'October - March',
  String openingHours = 'Open daily',
  double rating = 4.0,
  int reviews = 200,
  List<String> tags = const ['local', 'scenic'],
  List<String> images = const [],
  List<String> videos = const [],
}) {
  return {
    'name': name,
    'name_bn': nameBn,
    'description': description,
    'images': images,
    'videos': videos,
    'entry_fee': entryFee,
    'is_free_entry': isFree,
    'visit_duration': visitDuration,
    'best_time': bestTime,
    'opening_hours': openingHours,
    'latitude': lat,
    'longitude': lng,
    'rating': rating,
    'review_count': reviews,
    'tags': tags,
  };
}
